#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Filename: constant
# @Date: 8/8/2017
# @Author: Mark Wang
# @Email: wangyouan@gamil.com


class StateName(object):
    """ This file stores all the states name that would be used in this calculator """

    MAINE = "Maine"
    HAWAII = "Hawaii"
    ARIZONA = "Arizona"
    ARKANSAS = "Arkansas"
    DELAWARE = "Delaware"
    GEORGIA = "Georgia"
    MINNESOTA = "Minnesota"
    ALASKA = "Alaska"
    CALIFORNIA = "California"
    DISTRICT_OF_COLUMBIA = "District of Columbia"
    FLORIDA = "Florida"
    IDAHO = "Idaho"
    ILLINOIS = "Illinois"
    IOWA = "Iowa"
    KENTUCKY = "Kentucky"
    LOUISIANA = "Louisiana"
    MARYLAND = "Maryland"
    MICHIGAN = "Michigan"
    MISSOURI = "Missouri"
    MONTANA = "Montana"
    NEW_YORK = "New York"
    OREGON = "Oregon"
    TENNESSEE = "Tennessee"
    TEXAS = "Texas"
    VIRGINIA = "Virginia"
    WISCONSIN = "Wisconsin"
    SOUTH_DAKOTA = "South Dakota"
    UTAH = "Utah"
    INDIANA = "Indiana"
    MASSACHUSETTS = "Massachusetts"
    MISSISSIPPI = "Mississippi"
    NEBRASKA = "Nebraska"
    NEW_MEXICO = "New Mexico"
    NORTH_CAROLINA = "North Carolina"
    RHODE_ISLAND = "Rhode Island"
    OHIO = "Ohio"
    OKLAHOMA = "Oklahoma"
    SOUTH_CAROLINA = "South Carolina"
    COLORADO = "Colorado"
    KANSAS = "Kansas"
    CONNECTICUT = "Connecticut"
    NEVADA = "Nevada"
    WASHINGTON = "Washington"
    WEST_VIRGINIA = "West Virginia"
    WYOMING = "Wyoming"
    ALABAMA = "Alabama"
    PUERTO_RICO = "Puerto Rico"
    NEW_HAMPSHIRE = "New Hampshire"
    NEW_JERSEY = "New Jersey"
    NORTH_DAKOTA = "North Dakota"
    PENNSYLVANIA = "Pennsylvania"
    VERMONT = "Vermont"